// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createApiToken = `-- name: CreateApiToken :exec
INSERT INTO api_tokens (user_id, token_hash, expires_at, client_ip, created_at, last_used_at)
VALUES (?, ?, ?, ?, ?, NULL)
`

type CreateApiTokenParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt sql.NullTime
	ClientIp  sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) error {
	_, err := q.db.ExecContext(ctx, createApiToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.ClientIp,
		arg.CreatedAt,
	)
	return err
}

const deleteApiToken = `-- name: DeleteApiToken :exec
DELETE FROM api_tokens
WHERE id = ? AND user_id = ?
`

type DeleteApiTokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteApiToken(ctx context.Context, arg DeleteApiTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteApiToken, arg.ID, arg.UserID)
	return err
}

const findValidApiTokenByHash = `-- name: FindValidApiTokenByHash :one
SELECT id, user_id, token_hash, expires_at, client_ip, created_at, last_used_at
FROM api_tokens
WHERE token_hash = ? AND (expires_at IS NULL OR expires_at > ?)
`

type FindValidApiTokenByHashParams struct {
	TokenHash string
	ExpiresAt sql.NullTime
}

func (q *Queries) FindValidApiTokenByHash(ctx context.Context, arg FindValidApiTokenByHashParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, findValidApiTokenByHash, arg.TokenHash, arg.ExpiresAt)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClientIp,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listApiTokensByUser = `-- name: ListApiTokensByUser :many
SELECT id, user_id, token_hash, expires_at, client_ip, created_at, last_used_at
FROM api_tokens
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListApiTokensByUser(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listApiTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.ClientIp,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredApiTokens = `-- name: PurgeExpiredApiTokens :execresult
DELETE FROM api_tokens
WHERE expires_at IS NOT NULL AND expires_at <= ?
`

func (q *Queries) PurgeExpiredApiTokens(ctx context.Context, expiresAt sql.NullTime) (sql.Result, error) {
	return q.db.ExecContext(ctx, purgeExpiredApiTokens, expiresAt)
}

const touchApiTokenLastUsed = `-- name: TouchApiTokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = ?
WHERE id = ?
`

type TouchApiTokenLastUsedParams struct {
	LastUsedAt sql.NullTime
	ID         int64
}

func (q *Queries) TouchApiTokenLastUsed(ctx context.Context, arg TouchApiTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchApiTokenLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
