// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailboxes.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const clearTwoFactor = `-- name: ClearTwoFactor :exec
UPDATE mailboxes
SET totp_secret = NULL, recovery_codes = NULL, totp_last_step = NULL, updated_at = ?
WHERE id = ?
`

type ClearTwoFactorParams struct {
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) ClearTwoFactor(ctx context.Context, arg ClearTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, clearTwoFactor, arg.UpdatedAt, arg.ID)
	return err
}

const createMailbox = `-- name: CreateMailbox :execresult
INSERT INTO mailboxes (local_part, domain, address, password_hash, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMailboxParams struct {
	LocalPart    string
	Domain       string
	Address      string
	PasswordHash sql.NullString
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateMailbox(ctx context.Context, arg CreateMailboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMailbox,
		arg.LocalPart,
		arg.Domain,
		arg.Address,
		arg.PasswordHash,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const findMailboxByID = `-- name: FindMailboxByID :one
SELECT id, local_part, domain, address, password_hash, status, created_at, updated_at
FROM mailboxes
WHERE id = ?
`

type FindMailboxByIDRow struct {
	ID           int64
	LocalPart    string
	Domain       string
	Address      string
	PasswordHash sql.NullString
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) FindMailboxByID(ctx context.Context, id int64) (FindMailboxByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findMailboxByID, id)
	var i FindMailboxByIDRow
	err := row.Scan(
		&i.ID,
		&i.LocalPart,
		&i.Domain,
		&i.Address,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailboxByAddress = `-- name: GetMailboxByAddress :one
SELECT id, local_part, domain, address, password_hash, status, created_at, updated_at
FROM mailboxes
WHERE address = ?
`

type GetMailboxByAddressRow struct {
	ID           int64
	LocalPart    string
	Domain       string
	Address      string
	PasswordHash sql.NullString
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetMailboxByAddress(ctx context.Context, address string) (GetMailboxByAddressRow, error) {
	row := q.db.QueryRowContext(ctx, getMailboxByAddress, address)
	var i GetMailboxByAddressRow
	err := row.Scan(
		&i.ID,
		&i.LocalPart,
		&i.Domain,
		&i.Address,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTwoFactorByID = `-- name: GetTwoFactorByID :one
SELECT totp_secret, recovery_codes, two_factor_required, totp_last_step
FROM mailboxes
WHERE id = ?
`

type GetTwoFactorByIDRow struct {
	TotpSecret        sql.NullString
	RecoveryCodes     sql.NullString
	TwoFactorRequired bool
	TotpLastStep      sql.NullInt64
}

func (q *Queries) GetTwoFactorByID(ctx context.Context, id int64) (GetTwoFactorByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTwoFactorByID, id)
	var i GetTwoFactorByIDRow
	err := row.Scan(
		&i.TotpSecret,
		&i.RecoveryCodes,
		&i.TwoFactorRequired,
		&i.TotpLastStep,
	)
	return i, err
}

const listMailboxesByStatus = `-- name: ListMailboxesByStatus :many
SELECT id, local_part, domain, address, password_hash, status, created_at, updated_at
FROM mailboxes
WHERE status = ?
ORDER BY id
`

type ListMailboxesByStatusRow struct {
	ID           int64
	LocalPart    string
	Domain       string
	Address      string
	PasswordHash sql.NullString
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListMailboxesByStatus(ctx context.Context, status string) ([]ListMailboxesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listMailboxesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailboxesByStatusRow{}
	for rows.Next() {
		var i ListMailboxesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.LocalPart,
			&i.Domain,
			&i.Address,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTOTPStep = `-- name: MarkTOTPStep :exec
UPDATE mailboxes
SET totp_last_step = ?, updated_at = ?
WHERE id = ?
`

type MarkTOTPStepParams struct {
	TotpLastStep sql.NullInt64
	UpdatedAt    time.Time
	ID           int64
}

func (q *Queries) MarkTOTPStep(ctx context.Context, arg MarkTOTPStepParams) error {
	_, err := q.db.ExecContext(ctx, markTOTPStep, arg.TotpLastStep, arg.UpdatedAt, arg.ID)
	return err
}

const setMailboxCredentials = `-- name: SetMailboxCredentials :exec
UPDATE mailboxes
SET password_hash = ?, status = 'active', updated_at = ?
WHERE id = ?
`

type SetMailboxCredentialsParams struct {
	PasswordHash sql.NullString
	UpdatedAt    time.Time
	ID           int64
}

func (q *Queries) SetMailboxCredentials(ctx context.Context, arg SetMailboxCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, setMailboxCredentials, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const setMailboxStatus = `-- name: SetMailboxStatus :exec
UPDATE mailboxes
SET status = ?, updated_at = ?
WHERE id = ?
`

type SetMailboxStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) SetMailboxStatus(ctx context.Context, arg SetMailboxStatusParams) error {
	_, err := q.db.ExecContext(ctx, setMailboxStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const setTwoFactorRequired = `-- name: SetTwoFactorRequired :exec
UPDATE mailboxes
SET two_factor_required = ?, updated_at = ?
WHERE id = ?
`

type SetTwoFactorRequiredParams struct {
	TwoFactorRequired bool
	UpdatedAt         time.Time
	ID                int64
}

func (q *Queries) SetTwoFactorRequired(ctx context.Context, arg SetTwoFactorRequiredParams) error {
	_, err := q.db.ExecContext(ctx, setTwoFactorRequired, arg.TwoFactorRequired, arg.UpdatedAt, arg.ID)
	return err
}

const setTwoFactorSecret = `-- name: SetTwoFactorSecret :exec
UPDATE mailboxes
SET totp_secret = ?, totp_last_step = NULL, updated_at = ?
WHERE id = ?
`

type SetTwoFactorSecretParams struct {
	TotpSecret sql.NullString
	UpdatedAt  time.Time
	ID         int64
}

func (q *Queries) SetTwoFactorSecret(ctx context.Context, arg SetTwoFactorSecretParams) error {
	_, err := q.db.ExecContext(ctx, setTwoFactorSecret, arg.TotpSecret, arg.UpdatedAt, arg.ID)
	return err
}

const updateRecoveryCodes = `-- name: UpdateRecoveryCodes :exec
UPDATE mailboxes
SET recovery_codes = ?, updated_at = ?
WHERE id = ?
`

type UpdateRecoveryCodesParams struct {
	RecoveryCodes sql.NullString
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) UpdateRecoveryCodes(ctx context.Context, arg UpdateRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, updateRecoveryCodes, arg.RecoveryCodes, arg.UpdatedAt, arg.ID)
	return err
}
