// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  sql.NullTime
	ClientIp   sql.NullString
	CreatedAt  time.Time
	LastUsedAt sql.NullTime
}

type DeliveryQueue struct {
	ID            int64
	MessageID     int64
	EnvelopeFrom  string
	RcptTo        string
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastSmtpCode  sql.NullInt32
	LastError     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	RetFull       bool
}

type Folder struct {
	ID        int64
	MailboxID int64
	Name      string
	Kind      string
	CreatedAt time.Time
}

type LoginAttempt struct {
	ID          int64
	SubjectKey  string
	Ip          sql.NullString
	Success     bool
	AttemptedAt time.Time
}

type Mailbox struct {
	ID                int64
	LocalPart         string
	Domain            string
	Address           string
	PasswordHash      sql.NullString
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	TotpSecret        sql.NullString
	RecoveryCodes     sql.NullString
	TwoFactorRequired bool
	TotpLastStep      sql.NullInt64
}

type MailboxKeyword struct {
	ID               int64
	MailboxMessageID int64
	Keyword          string
	CreatedAt        time.Time
}

type MailboxMessage struct {
	ID           int64
	MailboxID    int64
	MessageID    int64
	FolderID     int64
	Uid          int64
	IsRead       bool
	IsFlagged    bool
	Status       string
	CreatedAt    time.Time
	IsAnswered   bool
	IsDraft      bool
	InternalDate sql.NullTime
}

type Message struct {
	ID                int64
	MessageID         sql.NullString
	BlobKey           string
	RawSize           int64
	Subject           sql.NullString
	FromAddr          sql.NullString
	ToAddrs           sql.NullString
	CcAddrs           sql.NullString
	SentAt            sql.NullTime
	SpfResult         sql.NullString
	DkimResult        sql.NullString
	DmarcResult       sql.NullString
	ArcResult         sql.NullString
	AuthResultsHeader sql.NullString
	CreatedAt         time.Time
	BodyCache         sql.NullString
}

type Session struct {
	ID                string
	SubjectType       string
	SubjectID         int64
	Ip                sql.NullString
	UserAgent         sql.NullString
	CreatedAt         time.Time
	LastSeenAt        time.Time
	AbsoluteExpiresAt time.Time
	CsrfToken         sql.NullString
}

type SieveScript struct {
	ID        int64
	MailboxID int64
	Name      string
	Content   string
	IsActive  bool
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
