// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package dbgen

import (
	"context"
	"database/sql"
)

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
DELETE FROM login_attempts
WHERE subject_key = ?
`

func (q *Queries) ClearLoginAttempts(ctx context.Context, subjectKey string) error {
	_, err := q.db.ExecContext(ctx, clearLoginAttempts, subjectKey)
	return err
}

const countRecentFailedAttempts = `-- name: CountRecentFailedAttempts :one
SELECT COUNT(*)
FROM login_attempts
WHERE subject_key = ? AND success = 0 AND attempted_at > ?
`

type CountRecentFailedAttemptsParams struct {
	SubjectKey  string
	AttemptedAt string
}

func (q *Queries) CountRecentFailedAttempts(ctx context.Context, arg CountRecentFailedAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedAttempts, arg.SubjectKey, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const purgeOldLoginAttempts = `-- name: PurgeOldLoginAttempts :execrows
DELETE FROM login_attempts
WHERE attempted_at < ?
`

func (q *Queries) PurgeOldLoginAttempts(ctx context.Context, attemptedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldLoginAttempts, attemptedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :execresult
INSERT INTO login_attempts (subject_key, ip, success, attempted_at)
VALUES (?, ?, ?, ?)
`

type RecordLoginAttemptParams struct {
	SubjectKey  string
	Ip          sql.NullString
	Success     int64
	AttemptedAt string
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recordLoginAttempt,
		arg.SubjectKey,
		arg.Ip,
		arg.Success,
		arg.AttemptedAt,
	)
}
