// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
)

const countMessagesByFolder = `-- name: CountMessagesByFolder :one
SELECT COUNT(*) FROM mailbox_messages
WHERE mailbox_id = ? AND folder_id = ?
`

type CountMessagesByFolderParams struct {
	MailboxID int64
	FolderID  int64
}

func (q *Queries) CountMessagesByFolder(ctx context.Context, arg CountMessagesByFolderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesByFolder, arg.MailboxID, arg.FolderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteKeywordsByMessageID = `-- name: DeleteKeywordsByMessageID :exec
DELETE FROM mailbox_keywords
WHERE mailbox_message_id = ?
`

func (q *Queries) DeleteKeywordsByMessageID(ctx context.Context, mailboxMessageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteKeywordsByMessageID, mailboxMessageID)
	return err
}

const deleteKeywordsByMessageIDs = `-- name: DeleteKeywordsByMessageIDs :execrows
DELETE FROM mailbox_keywords
WHERE mailbox_message_id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteKeywordsByMessageIDs(ctx context.Context, ids []int64) (int64, error) {
	query := deleteKeywordsByMessageIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMailboxMessages = `-- name: DeleteMailboxMessages :execrows
DELETE FROM mailbox_messages
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteMailboxMessages(ctx context.Context, ids []int64) (int64, error) {
	query := deleteMailboxMessages
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOrphanMessages = `-- name: DeleteOrphanMessages :execrows
DELETE FROM messages
WHERE NOT EXISTS (
    SELECT 1 FROM mailbox_messages mm WHERE mm.message_id = messages.id
)
`

func (q *Queries) DeleteOrphanMessages(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanMessages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fillBodyCache = `-- name: FillBodyCache :execrows
UPDATE messages SET body_cache = ? WHERE id = ?
`

type FillBodyCacheParams struct {
	BodyCache sql.NullString
	ID        int64
}

func (q *Queries) FillBodyCache(ctx context.Context, arg FillBodyCacheParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fillBodyCache, arg.BodyCache, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMailboxMessageDetail = `-- name: GetMailboxMessageDetail :one
SELECT
    mm.id AS mm_id,
    mm.uid AS mm_uid,
    mm.mailbox_id AS mm_mailbox_id,
    mm.folder_id AS mm_folder_id,
    mm.message_id AS mm_message_pk,
    mm.is_read AS mm_is_read,
    mm.is_flagged AS mm_is_flagged,
    mm.is_answered AS mm_is_answered,
    mm.is_draft AS mm_is_draft,
    mm.status AS mm_status,
    mm.internal_date AS mm_internal_date,
    mm.created_at AS mm_created_at,
    m.blob_key AS m_blob_key,
    m.subject AS m_subject,
    m.from_addr AS m_from_addr,
    m.to_addrs AS m_to_addrs,
    m.cc_addrs AS m_cc_addrs,
    m.sent_at AS m_sent_at,
    m.raw_size AS m_raw_size
FROM mailbox_messages mm
JOIN messages m ON m.id = mm.message_id
WHERE mm.mailbox_id = ? AND mm.id = ?
`

type GetMailboxMessageDetailParams struct {
	MailboxID int64
	ID        int64
}

type GetMailboxMessageDetailRow struct {
	MmID           int64
	MmUid          int64
	MmMailboxID    int64
	MmFolderID     int64
	MmMessagePk    int64
	MmIsRead       bool
	MmIsFlagged    bool
	MmIsAnswered   bool
	MmIsDraft      bool
	MmStatus       string
	MmInternalDate interface{}
	MmCreatedAt    string
	MBlobKey       string
	MSubject       sql.NullString
	MFromAddr      sql.NullString
	MToAddrs       sql.NullString
	MCcAddrs       sql.NullString
	MSentAt        sql.NullString
	MRawSize       int64
}

func (q *Queries) GetMailboxMessageDetail(ctx context.Context, arg GetMailboxMessageDetailParams) (GetMailboxMessageDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getMailboxMessageDetail, arg.MailboxID, arg.ID)
	var i GetMailboxMessageDetailRow
	err := row.Scan(
		&i.MmID,
		&i.MmUid,
		&i.MmMailboxID,
		&i.MmFolderID,
		&i.MmMessagePk,
		&i.MmIsRead,
		&i.MmIsFlagged,
		&i.MmIsAnswered,
		&i.MmIsDraft,
		&i.MmStatus,
		&i.MmInternalDate,
		&i.MmCreatedAt,
		&i.MBlobKey,
		&i.MSubject,
		&i.MFromAddr,
		&i.MToAddrs,
		&i.MCcAddrs,
		&i.MSentAt,
		&i.MRawSize,
	)
	return i, err
}

const getMailboxMessageFlags = `-- name: GetMailboxMessageFlags :one
SELECT id, mailbox_id, is_read, is_flagged, is_answered, is_draft, status
FROM mailbox_messages
WHERE id = ?
`

type GetMailboxMessageFlagsRow struct {
	ID         int64
	MailboxID  int64
	IsRead     bool
	IsFlagged  bool
	IsAnswered bool
	IsDraft    bool
	Status     string
}

func (q *Queries) GetMailboxMessageFlags(ctx context.Context, id int64) (GetMailboxMessageFlagsRow, error) {
	row := q.db.QueryRowContext(ctx, getMailboxMessageFlags, id)
	var i GetMailboxMessageFlagsRow
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.IsRead,
		&i.IsFlagged,
		&i.IsAnswered,
		&i.IsDraft,
		&i.Status,
	)
	return i, err
}

const getMailboxMessageIDByUID = `-- name: GetMailboxMessageIDByUID :one
SELECT id FROM mailbox_messages
WHERE mailbox_id = ? AND uid = ?
`

type GetMailboxMessageIDByUIDParams struct {
	MailboxID int64
	Uid       int64
}

func (q *Queries) GetMailboxMessageIDByUID(ctx context.Context, arg GetMailboxMessageIDByUIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMailboxMessageIDByUID, arg.MailboxID, arg.Uid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMailboxMessageRows = `-- name: GetMailboxMessageRows :many

SELECT id, message_id, folder_id
FROM mailbox_messages
WHERE id IN (/*SLICE:ids*/?)
`

type GetMailboxMessageRowsRow struct {
	ID        int64
	MessageID int64
	FolderID  int64
}

// U25 delete cascade (FR-003/Q2 directive): removing an aggregate-folder row also
// removes every sibling mailbox_messages row of the same messages entity. Split
// into single-table queries to sidestep sqlc engine JOIN+slice rewrite limits.
// fetch row metadata (id, message_id, folder_id) for folder-membership decision
func (q *Queries) GetMailboxMessageRows(ctx context.Context, ids []int64) ([]GetMailboxMessageRowsRow, error) {
	query := getMailboxMessageRows
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMailboxMessageRowsRow{}
	for rows.Next() {
		var i GetMailboxMessageRowsRow
		if err := rows.Scan(&i.ID, &i.MessageID, &i.FolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxMailboxUID = `-- name: GetMaxMailboxUID :one
SELECT COALESCE(MAX(uid), 0) FROM mailbox_messages WHERE mailbox_id = ?
`

func (q *Queries) GetMaxMailboxUID(ctx context.Context, mailboxID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxMailboxUID, mailboxID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const insertMailboxKeyword = `-- name: InsertMailboxKeyword :exec

INSERT INTO mailbox_keywords (mailbox_message_id, keyword, created_at)
VALUES (?, ?, ?)
`

type InsertMailboxKeywordParams struct {
	MailboxMessageID int64
	Keyword          string
	CreatedAt        string
}

// D8 keyword storage (table mailbox_keywords, migration 00008)
func (q *Queries) InsertMailboxKeyword(ctx context.Context, arg InsertMailboxKeywordParams) error {
	_, err := q.db.ExecContext(ctx, insertMailboxKeyword, arg.MailboxMessageID, arg.Keyword, arg.CreatedAt)
	return err
}

const insertMailboxMessage = `-- name: InsertMailboxMessage :execresult
INSERT INTO mailbox_messages (mailbox_id, message_id, folder_id, uid, is_read, is_flagged, status, created_at)
VALUES (?, ?, ?, ?, 0, 0, 'normal', ?)
`

type InsertMailboxMessageParams struct {
	MailboxID int64
	MessageID int64
	FolderID  int64
	Uid       int64
	CreatedAt string
}

func (q *Queries) InsertMailboxMessage(ctx context.Context, arg InsertMailboxMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMailboxMessage,
		arg.MailboxID,
		arg.MessageID,
		arg.FolderID,
		arg.Uid,
		arg.CreatedAt,
	)
}

const insertMailboxMessageWithFlags = `-- name: InsertMailboxMessageWithFlags :execresult
INSERT INTO mailbox_messages (mailbox_id, message_id, folder_id, uid, is_read, is_flagged, is_answered, is_draft, status, internal_date, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMailboxMessageWithFlagsParams struct {
	MailboxID    int64
	MessageID    int64
	FolderID     int64
	Uid          int64
	IsRead       bool
	IsFlagged    bool
	IsAnswered   bool
	IsDraft      bool
	Status       string
	InternalDate interface{}
	CreatedAt    string
}

func (q *Queries) InsertMailboxMessageWithFlags(ctx context.Context, arg InsertMailboxMessageWithFlagsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMailboxMessageWithFlags,
		arg.MailboxID,
		arg.MessageID,
		arg.FolderID,
		arg.Uid,
		arg.IsRead,
		arg.IsFlagged,
		arg.IsAnswered,
		arg.IsDraft,
		arg.Status,
		arg.InternalDate,
		arg.CreatedAt,
	)
}

const insertMessage = `-- name: InsertMessage :execresult
INSERT INTO messages (message_id, blob_key, raw_size, subject, from_addr, to_addrs, cc_addrs, body_cache, sent_at, spf_result, dkim_result, dmarc_result, arc_result, auth_results_header, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	MessageID         sql.NullString
	BlobKey           string
	RawSize           int64
	Subject           sql.NullString
	FromAddr          sql.NullString
	ToAddrs           sql.NullString
	CcAddrs           sql.NullString
	BodyCache         sql.NullString
	SentAt            sql.NullString
	SpfResult         sql.NullString
	DkimResult        sql.NullString
	DmarcResult       sql.NullString
	ArcResult         sql.NullString
	AuthResultsHeader sql.NullString
	CreatedAt         string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMessage,
		arg.MessageID,
		arg.BlobKey,
		arg.RawSize,
		arg.Subject,
		arg.FromAddr,
		arg.ToAddrs,
		arg.CcAddrs,
		arg.BodyCache,
		arg.SentAt,
		arg.SpfResult,
		arg.DkimResult,
		arg.DmarcResult,
		arg.ArcResult,
		arg.AuthResultsHeader,
		arg.CreatedAt,
	)
}

const listAggregateFolderIDs = `-- name: ListAggregateFolderIDs :many
SELECT id FROM folders WHERE kind = 'unregistered'
`

// all aggregate folder ids (kind=unregistered, postmaster-owned)
func (q *Queries) ListAggregateFolderIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAggregateFolderIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBodyCachePending = `-- name: ListBodyCachePending :many
SELECT id, blob_key FROM messages WHERE body_cache IS NULL LIMIT ?
`

type ListBodyCachePendingRow struct {
	ID      int64
	BlobKey string
}

func (q *Queries) ListBodyCachePending(ctx context.Context, limit int64) ([]ListBodyCachePendingRow, error) {
	rows, err := q.db.QueryContext(ctx, listBodyCachePending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBodyCachePendingRow{}
	for rows.Next() {
		var i ListBodyCachePendingRow
		if err := rows.Scan(&i.ID, &i.BlobKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderUIDsASC = `-- name: ListFolderUIDsASC :many
SELECT uid FROM mailbox_messages
WHERE mailbox_id = ? AND folder_id = ?
ORDER BY uid ASC
`

type ListFolderUIDsASCParams struct {
	MailboxID int64
	FolderID  int64
}

func (q *Queries) ListFolderUIDsASC(ctx context.Context, arg ListFolderUIDsASCParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listFolderUIDsASC, arg.MailboxID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var uid int64
		if err := rows.Scan(&uid); err != nil {
			return nil, err
		}
		items = append(items, uid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageKeywords = `-- name: ListMessageKeywords :many
SELECT keyword FROM mailbox_keywords
WHERE mailbox_message_id = ?
ORDER BY keyword
`

func (q *Queries) ListMessageKeywords(ctx context.Context, mailboxMessageID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMessageKeywords, mailboxMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var keyword string
		if err := rows.Scan(&keyword); err != nil {
			return nil, err
		}
		items = append(items, keyword)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByFolderPage = `-- name: ListMessagesByFolderPage :many
SELECT
    mm.id AS mm_id,
    mm.uid AS mm_uid,
    mm.is_read AS mm_is_read,
    mm.is_flagged AS mm_is_flagged,
    mm.status AS mm_status,
    m.subject AS m_subject,
    m.from_addr AS m_from_addr,
    m.sent_at AS m_sent_at,
    m.blob_key AS m_blob_key,
    m.raw_size AS m_raw_size
FROM mailbox_messages mm
JOIN messages m ON m.id = mm.message_id
WHERE mm.mailbox_id = ? AND mm.folder_id = ?
ORDER BY mm.uid DESC
LIMIT ? OFFSET ?
`

type ListMessagesByFolderPageParams struct {
	MailboxID int64
	FolderID  int64
	Limit     int64
	Offset    int64
}

type ListMessagesByFolderPageRow struct {
	MmID        int64
	MmUid       int64
	MmIsRead    bool
	MmIsFlagged bool
	MmStatus    string
	MSubject    sql.NullString
	MFromAddr   sql.NullString
	MSentAt     sql.NullString
	MBlobKey    string
	MRawSize    int64
}

func (q *Queries) ListMessagesByFolderPage(ctx context.Context, arg ListMessagesByFolderPageParams) ([]ListMessagesByFolderPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByFolderPage,
		arg.MailboxID,
		arg.FolderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByFolderPageRow{}
	for rows.Next() {
		var i ListMessagesByFolderPageRow
		if err := rows.Scan(
			&i.MmID,
			&i.MmUid,
			&i.MmIsRead,
			&i.MmIsFlagged,
			&i.MmStatus,
			&i.MSubject,
			&i.MFromAddr,
			&i.MSentAt,
			&i.MBlobKey,
			&i.MRawSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShadowBackfill = `-- name: ListShadowBackfill :many

SELECT DISTINCT mm.message_id
FROM mailbox_messages mm
JOIN mailboxes mb ON mb.id = mm.mailbox_id AND mb.status = 'shadow'
WHERE NOT EXISTS (
    SELECT 1
    FROM mailbox_messages agg
    JOIN folders af ON af.id = agg.folder_id AND af.kind = 'unregistered'
    WHERE agg.message_id = mm.message_id
)
ORDER BY mm.message_id
LIMIT ?
`

// U25 shadow aggregate reachability (FR-003 carry expansion, S3-W Q1-B/Q4)
// pending backfill: message ids archived in shadow mailboxes without an
// aggregate copy yet (DISTINCT: one aggregate row per messages entity;
// NOT EXISTS makes re-runs naturally idempotent)
func (q *Queries) ListShadowBackfill(ctx context.Context, limit int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listShadowBackfill, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var message_id int64
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailboxMessagesDeleted = `-- name: MarkMailboxMessagesDeleted :execrows
UPDATE mailbox_messages
SET status = 'deleted'
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) MarkMailboxMessagesDeleted(ctx context.Context, ids []int64) (int64, error) {
	query := markMailboxMessagesDeleted
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const moveMailboxMessage = `-- name: MoveMailboxMessage :execrows
UPDATE mailbox_messages
SET folder_id = ?
WHERE id = ?
`

type MoveMailboxMessageParams struct {
	FolderID int64
	ID       int64
}

func (q *Queries) MoveMailboxMessage(ctx context.Context, arg MoveMailboxMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveMailboxMessage, arg.FolderID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectIDsByMessageIDs = `-- name: SelectIDsByMessageIDs :many
SELECT DISTINCT id
FROM mailbox_messages
WHERE message_id IN (/*SLICE:messageIDs*/?)
`

// sibling row ids sharing the same messages entity (caller excludes originals)
func (q *Queries) SelectIDsByMessageIDs(ctx context.Context, messageids []int64) ([]int64, error) {
	query := selectIDsByMessageIDs
	var queryParams []interface{}
	if len(messageids) > 0 {
		for _, v := range messageids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:messageIDs*/?", strings.Repeat(",?", len(messageids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:messageIDs*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMailboxMessageFlags = `-- name: UpdateMailboxMessageFlags :execrows
UPDATE mailbox_messages
SET is_read = ?, is_flagged = ?, is_answered = ?, is_draft = ?, status = ?
WHERE id = ?
`

type UpdateMailboxMessageFlagsParams struct {
	IsRead     bool
	IsFlagged  bool
	IsAnswered bool
	IsDraft    bool
	Status     string
	ID         int64
}

func (q *Queries) UpdateMailboxMessageFlags(ctx context.Context, arg UpdateMailboxMessageFlagsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMailboxMessageFlags,
		arg.IsRead,
		arg.IsFlagged,
		arg.IsAnswered,
		arg.IsDraft,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
