// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package dbgen

import (
	"context"
	"database/sql"
)

const claimDueQueueItems = `-- name: ClaimDueQueueItems :many
UPDATE delivery_queue
SET status = 'in_flight', updated_at = ?
WHERE id IN (
    SELECT due.id FROM delivery_queue AS due
    WHERE due.status IN ('pending', 'deferred') AND due.next_attempt_at <= ?
    ORDER BY due.next_attempt_at, due.id
    LIMIT ?
)
RETURNING id, message_id, envelope_from, rcpt_to, status, attempts, next_attempt_at, last_smtp_code, last_error, created_at, updated_at, ret_full
`

type ClaimDueQueueItemsParams struct {
	UpdatedAt     string
	NextAttemptAt string
	Limit         int64
}

func (q *Queries) ClaimDueQueueItems(ctx context.Context, arg ClaimDueQueueItemsParams) ([]DeliveryQueue, error) {
	rows, err := q.db.QueryContext(ctx, claimDueQueueItems, arg.UpdatedAt, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryQueue{}
	for rows.Next() {
		var i DeliveryQueue
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.EnvelopeFrom,
			&i.RcptTo,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastSmtpCode,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT id, message_id, envelope_from, rcpt_to, status, attempts, next_attempt_at, last_smtp_code, last_error, created_at, updated_at, ret_full
FROM delivery_queue WHERE id = ?
`

func (q *Queries) GetQueueItem(ctx context.Context, id int64) (DeliveryQueue, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, id)
	var i DeliveryQueue
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.EnvelopeFrom,
		&i.RcptTo,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastSmtpCode,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetFull,
	)
	return i, err
}

const insertQueueItem = `-- name: InsertQueueItem :execresult
INSERT INTO delivery_queue (message_id, envelope_from, rcpt_to, status, attempts, next_attempt_at, ret_full, created_at, updated_at)
VALUES (?, ?, ?, ?, 0, ?, ?, ?, ?)
`

type InsertQueueItemParams struct {
	MessageID     int64
	EnvelopeFrom  string
	RcptTo        string
	Status        string
	NextAttemptAt string
	RetFull       bool
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) InsertQueueItem(ctx context.Context, arg InsertQueueItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertQueueItem,
		arg.MessageID,
		arg.EnvelopeFrom,
		arg.RcptTo,
		arg.Status,
		arg.NextAttemptAt,
		arg.RetFull,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const markQueueResult = `-- name: MarkQueueResult :execresult
UPDATE delivery_queue
SET status = ?, attempts = ?, next_attempt_at = ?, last_smtp_code = ?, last_error = ?, updated_at = ?
WHERE id = ?
`

type MarkQueueResultParams struct {
	Status        string
	Attempts      int64
	NextAttemptAt string
	LastSmtpCode  sql.NullInt64
	LastError     sql.NullString
	UpdatedAt     string
	ID            int64
}

func (q *Queries) MarkQueueResult(ctx context.Context, arg MarkQueueResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markQueueResult,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastSmtpCode,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
}

const reclaimStaleQueueItems = `-- name: ReclaimStaleQueueItems :execresult
UPDATE delivery_queue
SET status = 'pending', updated_at = ?
WHERE status = 'in_flight' AND updated_at < ?
`

type ReclaimStaleQueueItemsParams struct {
	UpdatedAt   string
	UpdatedAt_2 string
}

func (q *Queries) ReclaimStaleQueueItems(ctx context.Context, arg ReclaimStaleQueueItemsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reclaimStaleQueueItems, arg.UpdatedAt, arg.UpdatedAt_2)
}
