// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :execresult
INSERT INTO sessions (id, subject_type, subject_id, ip, user_agent, csrf_token, created_at, last_seen_at, absolute_expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID                string
	SubjectType       string
	SubjectID         int64
	Ip                sql.NullString
	UserAgent         sql.NullString
	CsrfToken         sql.NullString
	CreatedAt         string
	LastSeenAt        string
	AbsoluteExpiresAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Ip,
		arg.UserAgent,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.AbsoluteExpiresAt,
	)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionByIDHash = `-- name: GetSessionByIDHash :one
SELECT id, subject_type, subject_id, ip, user_agent, csrf_token, created_at, last_seen_at, absolute_expires_at
FROM sessions
WHERE id = ?
`

type GetSessionByIDHashRow struct {
	ID                string
	SubjectType       string
	SubjectID         int64
	Ip                sql.NullString
	UserAgent         sql.NullString
	CsrfToken         sql.NullString
	CreatedAt         string
	LastSeenAt        string
	AbsoluteExpiresAt string
}

func (q *Queries) GetSessionByIDHash(ctx context.Context, id string) (GetSessionByIDHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByIDHash, id)
	var i GetSessionByIDHashRow
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Ip,
		&i.UserAgent,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM sessions
WHERE absolute_expires_at < ?
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context, absoluteExpiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredSessions, absoluteExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = ?, ip = ?, user_agent = ?
WHERE id = ?
`

type TouchSessionParams struct {
	LastSeenAt string
	Ip         sql.NullString
	UserAgent  sql.NullString
	ID         string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession,
		arg.LastSeenAt,
		arg.Ip,
		arg.UserAgent,
		arg.ID,
	)
	return err
}
