// GRmail 插件 gRPC 契约（FR-016；SRS 3.10.1；IR-006）
// 依据：U15 计划书 v1.0.0 1.5①（Q2-A 最小完备钩子集裁决 2026-09-24 10:43:43）；
// REQ-023 裁决「独立进程+gRPC…HashiCorp go-plugin」（2026-09-15 10:28:29）。
// 契约性质：本文件为插件接口签名唯一事实来源（NFR-014——主程序与插件均仅经
// 生成代码消费；契约变更→重新生成→主程序重编译即适配，无额外耦合改动）。
// 生成：make generate-proto（protoc+protoc-gen-go+protoc-gen-go-grpc；生成物入库）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/grmail_plugin.proto

package grmailplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetInfoRequest 元信息请求（无参——插件自述）。
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{0}
}

// PluginInfo 插件元信息。
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                 // 插件名（日志与监管呈现）
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`           // 插件版本
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // 能力声明：inbound_hook/submit_hook/protocol
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// InboundContext 收信钩子输入（验证结论+原始字节——DATA 完成态，未含宿主注入头）。
type InboundContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`                       // SMTP 会话信封
	Verification  *VerifyResults         `protobuf:"bytes,2,opt,name=verification,proto3" json:"verification,omitempty"`               // 四项验证结论（SPF/DKIM/DMARC/ARC）
	RawMessage    []byte                 `protobuf:"bytes,3,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"` // 原始邮件字节（保真）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundContext) Reset() {
	*x = InboundContext{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundContext) ProtoMessage() {}

func (x *InboundContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundContext.ProtoReflect.Descriptor instead.
func (*InboundContext) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InboundContext) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *InboundContext) GetVerification() *VerifyResults {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *InboundContext) GetRawMessage() []byte {
	if x != nil {
		return x.RawMessage
	}
	return nil
}

// SubmitContext 发信钩子输入（提交会话形态）。
type SubmitContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`                       // SMTP 会话信封
	AuthUser      string                 `protobuf:"bytes,2,opt,name=auth_user,json=authUser,proto3" json:"auth_user,omitempty"`       // 认证身份（邮箱地址或管理员用户名，FR-002 授权判定输入）
	Recipients    []string               `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`                   // RCPT TO 全量收件人
	RawMessage    []byte                 `protobuf:"bytes,4,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"` // 提交原始字节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitContext) Reset() {
	*x = SubmitContext{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitContext) ProtoMessage() {}

func (x *SubmitContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitContext.ProtoReflect.Descriptor instead.
func (*SubmitContext) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitContext) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SubmitContext) GetAuthUser() string {
	if x != nil {
		return x.AuthUser
	}
	return ""
}

func (x *SubmitContext) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SubmitContext) GetRawMessage() []byte {
	if x != nil {
		return x.RawMessage
	}
	return nil
}

// Envelope SMTP 信封三元组。
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Helo          string                 `protobuf:"bytes,1,opt,name=helo,proto3" json:"helo,omitempty"`                         // EHLO 名
	RemoteIp      string                 `protobuf:"bytes,2,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"` // 对端 IP
	MailFrom      string                 `protobuf:"bytes,3,opt,name=mail_from,json=mailFrom,proto3" json:"mail_from,omitempty"` // MAIL FROM（空=<> null path）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Envelope) GetHelo() string {
	if x != nil {
		return x.Helo
	}
	return ""
}

func (x *Envelope) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *Envelope) GetMailFrom() string {
	if x != nil {
		return x.MailFrom
	}
	return ""
}

// VerifyResults 四项验证结论（none|pass|fail|softfail|temperror|permerror...）。
type VerifyResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spf           string                 `protobuf:"bytes,1,opt,name=spf,proto3" json:"spf,omitempty"`
	Dkim          string                 `protobuf:"bytes,2,opt,name=dkim,proto3" json:"dkim,omitempty"`
	Dmarc         string                 `protobuf:"bytes,3,opt,name=dmarc,proto3" json:"dmarc,omitempty"`
	Arc           string                 `protobuf:"bytes,4,opt,name=arc,proto3" json:"arc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResults) Reset() {
	*x = VerifyResults{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResults) ProtoMessage() {}

func (x *VerifyResults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResults.ProtoReflect.Descriptor instead.
func (*VerifyResults) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyResults) GetSpf() string {
	if x != nil {
		return x.Spf
	}
	return ""
}

func (x *VerifyResults) GetDkim() string {
	if x != nil {
		return x.Dkim
	}
	return ""
}

func (x *VerifyResults) GetDmarc() string {
	if x != nil {
		return x.Dmarc
	}
	return ""
}

func (x *VerifyResults) GetArc() string {
	if x != nil {
		return x.Arc
	}
	return ""
}

// HookDecision 钩子决策。
type HookDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`                       // true=放行；false=拒绝
	SmtpCode      int32                  `protobuf:"varint,2,opt,name=smtp_code,json=smtpCode,proto3" json:"smtp_code,omitempty"` // 拒绝应答码（400-599；宿主校验越界按放行+告警）
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                    // 拒绝原因（对端应答文本）/说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookDecision) Reset() {
	*x = HookDecision{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookDecision) ProtoMessage() {}

func (x *HookDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookDecision.ProtoReflect.Descriptor instead.
func (*HookDecision) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HookDecision) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *HookDecision) GetSmtpCode() int32 {
	if x != nil {
		return x.SmtpCode
	}
	return 0
}

func (x *HookDecision) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ProtocolRegistration 协议注册声明（返回流消息——插件→宿主方向）。
type ProtocolRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolName  string                 `protobuf:"bytes,1,opt,name=protocol_name,json=protocolName,proto3" json:"protocol_name,omitempty"` // 协议名（如 caldav/carddav——FR-017 形态预留）
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                             // 建议端点路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolRegistration) Reset() {
	*x = ProtocolRegistration{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolRegistration) ProtoMessage() {}

func (x *ProtocolRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolRegistration.ProtoReflect.Descriptor instead.
func (*ProtocolRegistration) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ProtocolRegistration) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

func (x *ProtocolRegistration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// ProtocolAck 协议注册确认（请求流消息——宿主→插件回执方向）。
type ProtocolAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 登记结果（本期恒 true——登记不路由）
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`          // 备注（宿主登记说明）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolAck) Reset() {
	*x = ProtocolAck{}
	mi := &file_proto_grmail_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolAck) ProtoMessage() {}

func (x *ProtocolAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grmail_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolAck.ProtoReflect.Descriptor instead.
func (*ProtocolAck) Descriptor() ([]byte, []int) {
	return file_proto_grmail_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ProtocolAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ProtocolAck) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_proto_grmail_plugin_proto protoreflect.FileDescriptor

const file_proto_grmail_plugin_proto_rawDesc = "" +
	"\n" +
	"\x19proto/grmail_plugin.proto\x12\x10grmail.plugin.v1\"\x10\n" +
	"\x0eGetInfoRequest\"^\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xae\x01\n" +
	"\x0eInboundContext\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.grmail.plugin.v1.EnvelopeR\benvelope\x12C\n" +
	"\fverification\x18\x02 \x01(\v2\x1f.grmail.plugin.v1.VerifyResultsR\fverification\x12\x1f\n" +
	"\vraw_message\x18\x03 \x01(\fR\n" +
	"rawMessage\"\xa5\x01\n" +
	"\rSubmitContext\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.grmail.plugin.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\tauth_user\x18\x02 \x01(\tR\bauthUser\x12\x1e\n" +
	"\n" +
	"recipients\x18\x03 \x03(\tR\n" +
	"recipients\x12\x1f\n" +
	"\vraw_message\x18\x04 \x01(\fR\n" +
	"rawMessage\"X\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04helo\x18\x01 \x01(\tR\x04helo\x12\x1b\n" +
	"\tremote_ip\x18\x02 \x01(\tR\bremoteIp\x12\x1b\n" +
	"\tmail_from\x18\x03 \x01(\tR\bmailFrom\"]\n" +
	"\rVerifyResults\x12\x10\n" +
	"\x03spf\x18\x01 \x01(\tR\x03spf\x12\x12\n" +
	"\x04dkim\x18\x02 \x01(\tR\x04dkim\x12\x14\n" +
	"\x05dmarc\x18\x03 \x01(\tR\x05dmarc\x12\x10\n" +
	"\x03arc\x18\x04 \x01(\tR\x03arc\"[\n" +
	"\fHookDecision\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x1b\n" +
	"\tsmtp_code\x18\x02 \x01(\x05R\bsmtpCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"W\n" +
	"\x14ProtocolRegistration\x12#\n" +
	"\rprotocol_name\x18\x01 \x01(\tR\fprotocolName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"=\n" +
	"\vProtocolAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note2\xd4\x02\n" +
	"\fGRmailPlugin\x12I\n" +
	"\aGetInfo\x12 .grmail.plugin.v1.GetInfoRequest\x1a\x1c.grmail.plugin.v1.PluginInfo\x12M\n" +
	"\tOnInbound\x12 .grmail.plugin.v1.InboundContext\x1a\x1e.grmail.plugin.v1.HookDecision\x12K\n" +
	"\bOnSubmit\x12\x1f.grmail.plugin.v1.SubmitContext\x1a\x1e.grmail.plugin.v1.HookDecision\x12]\n" +
	"\x10RegisterProtocol\x12\x1d.grmail.plugin.v1.ProtocolAck\x1a&.grmail.plugin.v1.ProtocolRegistration(\x010\x01B\x1bZ\x19GRmail/proto/grmailpluginb\x06proto3"

var (
	file_proto_grmail_plugin_proto_rawDescOnce sync.Once
	file_proto_grmail_plugin_proto_rawDescData []byte
)

func file_proto_grmail_plugin_proto_rawDescGZIP() []byte {
	file_proto_grmail_plugin_proto_rawDescOnce.Do(func() {
		file_proto_grmail_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grmail_plugin_proto_rawDesc), len(file_proto_grmail_plugin_proto_rawDesc)))
	})
	return file_proto_grmail_plugin_proto_rawDescData
}

var file_proto_grmail_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_grmail_plugin_proto_goTypes = []any{
	(*GetInfoRequest)(nil),       // 0: grmail.plugin.v1.GetInfoRequest
	(*PluginInfo)(nil),           // 1: grmail.plugin.v1.PluginInfo
	(*InboundContext)(nil),       // 2: grmail.plugin.v1.InboundContext
	(*SubmitContext)(nil),        // 3: grmail.plugin.v1.SubmitContext
	(*Envelope)(nil),             // 4: grmail.plugin.v1.Envelope
	(*VerifyResults)(nil),        // 5: grmail.plugin.v1.VerifyResults
	(*HookDecision)(nil),         // 6: grmail.plugin.v1.HookDecision
	(*ProtocolRegistration)(nil), // 7: grmail.plugin.v1.ProtocolRegistration
	(*ProtocolAck)(nil),          // 8: grmail.plugin.v1.ProtocolAck
}
var file_proto_grmail_plugin_proto_depIdxs = []int32{
	4, // 0: grmail.plugin.v1.InboundContext.envelope:type_name -> grmail.plugin.v1.Envelope
	5, // 1: grmail.plugin.v1.InboundContext.verification:type_name -> grmail.plugin.v1.VerifyResults
	4, // 2: grmail.plugin.v1.SubmitContext.envelope:type_name -> grmail.plugin.v1.Envelope
	0, // 3: grmail.plugin.v1.GRmailPlugin.GetInfo:input_type -> grmail.plugin.v1.GetInfoRequest
	2, // 4: grmail.plugin.v1.GRmailPlugin.OnInbound:input_type -> grmail.plugin.v1.InboundContext
	3, // 5: grmail.plugin.v1.GRmailPlugin.OnSubmit:input_type -> grmail.plugin.v1.SubmitContext
	8, // 6: grmail.plugin.v1.GRmailPlugin.RegisterProtocol:input_type -> grmail.plugin.v1.ProtocolAck
	1, // 7: grmail.plugin.v1.GRmailPlugin.GetInfo:output_type -> grmail.plugin.v1.PluginInfo
	6, // 8: grmail.plugin.v1.GRmailPlugin.OnInbound:output_type -> grmail.plugin.v1.HookDecision
	6, // 9: grmail.plugin.v1.GRmailPlugin.OnSubmit:output_type -> grmail.plugin.v1.HookDecision
	7, // 10: grmail.plugin.v1.GRmailPlugin.RegisterProtocol:output_type -> grmail.plugin.v1.ProtocolRegistration
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_grmail_plugin_proto_init() }
func file_proto_grmail_plugin_proto_init() {
	if File_proto_grmail_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grmail_plugin_proto_rawDesc), len(file_proto_grmail_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grmail_plugin_proto_goTypes,
		DependencyIndexes: file_proto_grmail_plugin_proto_depIdxs,
		MessageInfos:      file_proto_grmail_plugin_proto_msgTypes,
	}.Build()
	File_proto_grmail_plugin_proto = out.File
	file_proto_grmail_plugin_proto_goTypes = nil
	file_proto_grmail_plugin_proto_depIdxs = nil
}
