// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const claimDueQueueItems = `-- name: ClaimDueQueueItems :many
UPDATE delivery_queue
SET status = 'in_flight', claim_token = $1, heartbeat_at = $2, updated_at = $3
WHERE id IN (
    SELECT due.id FROM delivery_queue AS due
    WHERE due.status IN ('pending', 'deferred') AND due.next_attempt_at <= $4
    ORDER BY due.next_attempt_at, due.id
    LIMIT $5
)
RETURNING id, message_id, envelope_from, rcpt_to, status, attempts, next_attempt_at, last_smtp_code, last_error, created_at, updated_at, ret_full, claim_token, skip_tls_policy
`

type ClaimDueQueueItemsParams struct {
	ClaimToken    sql.NullString
	HeartbeatAt   sql.NullTime
	UpdatedAt     time.Time
	NextAttemptAt time.Time
	Limit         int32
}

type ClaimDueQueueItemsRow struct {
	ID            int64
	MessageID     int64
	EnvelopeFrom  string
	RcptTo        string
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastSmtpCode  sql.NullInt32
	LastError     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	RetFull       bool
	ClaimToken    sql.NullString
	SkipTlsPolicy bool
}

// F4 (queue batch 3): claim token + heartbeat written atomically with the
// pending->in_flight transition; ReclaimStale judges staleness by
// COALESCE(heartbeat_at, updated_at).
func (q *Queries) ClaimDueQueueItems(ctx context.Context, arg ClaimDueQueueItemsParams) ([]ClaimDueQueueItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, claimDueQueueItems,
		arg.ClaimToken,
		arg.HeartbeatAt,
		arg.UpdatedAt,
		arg.NextAttemptAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueQueueItemsRow{}
	for rows.Next() {
		var i ClaimDueQueueItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.EnvelopeFrom,
			&i.RcptTo,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastSmtpCode,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetFull,
			&i.ClaimToken,
			&i.SkipTlsPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT id, message_id, envelope_from, rcpt_to, status, attempts, next_attempt_at, last_smtp_code, last_error, created_at, updated_at, ret_full, claim_token, skip_tls_policy
FROM delivery_queue WHERE id = $1
`

type GetQueueItemRow struct {
	ID            int64
	MessageID     int64
	EnvelopeFrom  string
	RcptTo        string
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastSmtpCode  sql.NullInt32
	LastError     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	RetFull       bool
	ClaimToken    sql.NullString
	SkipTlsPolicy bool
}

func (q *Queries) GetQueueItem(ctx context.Context, id int64) (GetQueueItemRow, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, id)
	var i GetQueueItemRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.EnvelopeFrom,
		&i.RcptTo,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastSmtpCode,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetFull,
		&i.ClaimToken,
		&i.SkipTlsPolicy,
	)
	return i, err
}

const heartbeatQueueClaim = `-- name: HeartbeatQueueClaim :execresult
UPDATE delivery_queue
SET heartbeat_at = $1, updated_at = $2
WHERE claim_token = $3 AND status = 'in_flight'
`

type HeartbeatQueueClaimParams struct {
	HeartbeatAt sql.NullTime
	UpdatedAt   time.Time
	ClaimToken  sql.NullString
}

// F4 (A-14-1/D1): renew heartbeat before each MX attempt (token-guarded).
func (q *Queries) HeartbeatQueueClaim(ctx context.Context, arg HeartbeatQueueClaimParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, heartbeatQueueClaim, arg.HeartbeatAt, arg.UpdatedAt, arg.ClaimToken)
}

const insertQueueItem = `-- name: InsertQueueItem :execresult
INSERT INTO delivery_queue (message_id, envelope_from, rcpt_to, status, attempts, next_attempt_at, ret_full, skip_tls_policy, created_at, updated_at)
VALUES ($1, $2, $3, $4, 0, $5, $6, $7, $8, $9)
`

type InsertQueueItemParams struct {
	MessageID     int64
	EnvelopeFrom  string
	RcptTo        string
	Status        string
	NextAttemptAt time.Time
	RetFull       bool
	SkipTlsPolicy bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertQueueItem(ctx context.Context, arg InsertQueueItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertQueueItem,
		arg.MessageID,
		arg.EnvelopeFrom,
		arg.RcptTo,
		arg.Status,
		arg.NextAttemptAt,
		arg.RetFull,
		arg.SkipTlsPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listFailedDSNPending = `-- name: ListFailedDSNPending :many
SELECT id, message_id, envelope_from, rcpt_to, status, attempts, next_attempt_at, last_smtp_code, last_error, created_at, updated_at, ret_full, claim_token, skip_tls_policy
FROM delivery_queue
WHERE status = 'failed' AND dsn_sent = FALSE
ORDER BY id
LIMIT $1
`

type ListFailedDSNPendingRow struct {
	ID            int64
	MessageID     int64
	EnvelopeFrom  string
	RcptTo        string
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastSmtpCode  sql.NullInt32
	LastError     sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	RetFull       bool
	ClaimToken    sql.NullString
	SkipTlsPolicy bool
}

// F5 (B-R2): rescan source for crashed-before-emitDSN failed rows.
func (q *Queries) ListFailedDSNPending(ctx context.Context, limit int32) ([]ListFailedDSNPendingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailedDSNPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailedDSNPendingRow{}
	for rows.Next() {
		var i ListFailedDSNPendingRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.EnvelopeFrom,
			&i.RcptTo,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastSmtpCode,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetFull,
			&i.ClaimToken,
			&i.SkipTlsPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQueueDSNSent = `-- name: MarkQueueDSNSent :execresult
UPDATE delivery_queue
SET dsn_sent = TRUE, updated_at = $1
WHERE id = $2 AND status = 'failed' AND dsn_sent = FALSE
`

type MarkQueueDSNSentParams struct {
	UpdatedAt time.Time
	ID        int64
}

// F5 (B-R2): DSN-issued marker on the failed row (idempotent guard).
func (q *Queries) MarkQueueDSNSent(ctx context.Context, arg MarkQueueDSNSentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markQueueDSNSent, arg.UpdatedAt, arg.ID)
}

const markQueueResult = `-- name: MarkQueueResult :execresult
UPDATE delivery_queue
SET status = $1, attempts = $2, next_attempt_at = $3, last_smtp_code = $4, last_error = $5, claim_token = NULL, heartbeat_at = NULL, updated_at = $6
WHERE id = $7 AND status = 'in_flight'
`

type MarkQueueResultParams struct {
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastSmtpCode  sql.NullInt32
	LastError     sql.NullString
	UpdatedAt     time.Time
	ID            int64
}

// F1 (A-14-2): guarded by status='in_flight'; late writes affect zero rows.
func (q *Queries) MarkQueueResult(ctx context.Context, arg MarkQueueResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markQueueResult,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastSmtpCode,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
}

const reclaimStaleQueueItems = `-- name: ReclaimStaleQueueItems :execresult
UPDATE delivery_queue
SET status = 'pending', claim_token = NULL, heartbeat_at = NULL, updated_at = $1,
    next_attempt_at = CASE attempts
        WHEN 0 THEN $2 WHEN 1 THEN $3 WHEN 2 THEN $4 WHEN 3 THEN $5
        WHEN 4 THEN $6 WHEN 5 THEN $7 ELSE $8 END
WHERE status = 'in_flight' AND COALESCE(heartbeat_at, updated_at) < $9
`

type ReclaimStaleQueueItemsParams struct {
	UpdatedAt       time.Time
	NextAttemptAt   time.Time
	NextAttemptAt_2 time.Time
	NextAttemptAt_3 time.Time
	NextAttemptAt_4 time.Time
	NextAttemptAt_5 time.Time
	NextAttemptAt_6 time.Time
	NextAttemptAt_7 time.Time
	HeartbeatAt     sql.NullTime
}

// F2 (A-14-3) + F4: reclaim resets next_attempt_at by the attempts-based
// backoff ladder (t0..t6 absolute timestamps from the repo layer).
func (q *Queries) ReclaimStaleQueueItems(ctx context.Context, arg ReclaimStaleQueueItemsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reclaimStaleQueueItems,
		arg.UpdatedAt,
		arg.NextAttemptAt,
		arg.NextAttemptAt_2,
		arg.NextAttemptAt_3,
		arg.NextAttemptAt_4,
		arg.NextAttemptAt_5,
		arg.NextAttemptAt_6,
		arg.NextAttemptAt_7,
		arg.HeartbeatAt,
	)
}
